name: Gutentag, World!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run
        run: go run cmd/gutentag-world/main.go

      - name: Verify output
        run: bash test.sh
